---
name: Load Parameters
description: Load parameters for the build job

outputs:
  build_matrix:
    description: Build matrix
    value: ${{ steps.set-matrix.outputs.build_matrix }}

  docker_image:
    description: Docker image
    value: ${{ steps.get-docker-image.outputs.image_name }}

  flat_build:
    description: Command to run for the flat build
    value: ${{ steps.set-build-command.outputs.flat_build }}

  sdk_build_command:
    description: Command to run for the SDK build
    value: ${{ steps.set-build-command.outputs.sdk_build_command }}

runs:
  using: "composite"
  steps:
    - name: Set Build Matrix
      id: set-matrix
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');

          const filePath = path.join(process.env.GITHUB_WORKSPACE, 'ci', 'MACHINES.json');

          if (!fs.existsSync(filePath)) {
            core.setFailed(`MACHINES.json not found at ${filePath}`);
            return;
          }

          let raw;
          try {
            raw = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
          } catch (err) {
            core.setFailed(`Failed to load or parse MACHINES.json: ${err.message}`);
            return;
          }

          // Normalize MACHINES.json into array items
          const normalizeEntry = (selector, value) => {
            const out = [];

            const pushItem = (obj) => {
              if (!obj || typeof obj !== 'object') return;
              const kas = obj.file_name;

              // ? REQUIRED CHANGE (only change)
              const machine = obj.machine_name;
              
              //get image_name
              const image = obj.image_name;

              // get test_enabled
              const testing_enabled = obj.testing_enabled

              if (!kas || typeof kas !== 'string') return;

              const kas_basename = kas.replace(/^.*\//, '').replace(/\.yml$/, '');
              out.push({ selector, kas_file: kas, kas_basename, machine_name: machine,image_name:image,testing_enabled:testing_enabled });
            };

            if (typeof value === 'string') {
              const kas = value;
              const kas_basename = kas.replace(/^.*\//, '').replace(/\.yml$/, '');
              out.push({ selector, kas_file: kas, kas_basename, machine_name: selector, image_name:image, testing_enabled:testing_enabled });
            } else if (Array.isArray(value)) {
              value.forEach(v => pushItem(v));
            } else if (typeof value === 'object' && value) {
              pushItem(value);
            }

            return out;
          };

          let matrix = [];
          for (const [selector, value] of Object.entries(raw)) {
            const items = normalizeEntry(selector, value) || [];
            matrix = matrix.concat(items);
          }

          if (matrix.length === 0) {
            core.setFailed('No entries produced from MACHINES.json after normalization.');
            return;
          }

          core.setOutput('build_matrix', JSON.stringify(matrix));
          console.log("Normalized build matrix:");
          console.log(JSON.stringify(matrix, null, 2));

    - name: Set the build commands
      id: set-build-command
      uses: actions/github-script@v7
      with:
        script: |
          const flat_build = 'bitbake qcom-multimedia-image';
          core.setOutput('flat_build', flat_build);
          console.log("FLAT BUILD COMMAND:", flat_build)

          const sdk = 'bitbake qcom-multimedia-image && bitbake qcom-multimedia-image -c populate_sdk';
          core.setOutput('sdk_build_command', sdk);
          console.log("SDK BUILD COMMAND:", sdk)

    - name: Update Summary
      shell: bash
      run: |
        echo "## Build Matrix" >> "$GITHUB_STEP_SUMMARY"
        echo "| Selector | Machine Name | KAS File | KAS Basename | IMAGE_NAME| TEST_ENABLED |" >> "$GITHUB_STEP_SUMMARY"
        echo "|---------|--------------|----------|--------------|--------------|------------|" >> "$GITHUB_STEP_SUMMARY"

        build_matrix='${{ steps.set-matrix.outputs.build_matrix }}'

        echo "$build_matrix" | jq -c '.[]' | while read -r entry; do
          selector=$(echo "$entry" | jq -r '.selector')
          machine_name=$(echo "$entry" | jq -r '.machine_name')
          kas_file=$(echo "$entry" | jq -r '.kas_file')
          kas_basename=$(echo "$entry" | jq -r '.kas_basename')
          image_name=$(echo "$entry" | jq -r '.image_name')
          testing_enabled=$(echo "$entry" | jq -r '.testing_enabled')

          echo "| ${selector} | ${machine_name} | ${kas_file} | ${kas_basename} | ${image_name}| ${testing_enabled} |" >> "$GITHUB_STEP_SUMMARY"
        done
